### ISSUE TITLE
Práctica 5

### ISSUE THREAD

**Issue by AricelCastro** [SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipoolaxd#1]
[practica 5..pdf](https://github.com/SistemasTecTlaxiaco/actividad-6-diseno-de-app-con-windows-form-equipoolaxd/files/14715428/practica.5.pdf)

**Comment by Aylin67** [comment]
17% Solo tienen 4 ilustraciones

**Comment by josealfredo79** [comment]
Bien hecho
